'use strict';

/**
 * runLogger.js — structured, persistent logging for scraper runs.
 *
 * Writes a summary row to `scrape_runs` (one per invocation) and a buffered event
 * stream to `scrape_events` (migration 011). Singleton — one logger per process.
 *
 * Design notes / adaptations to this repo:
 *   * Supabase client comes from db/supabase.getSupabaseClient() (the same
 *     service-role client the repositories use). If Supabase is unconfigured the
 *     client is null → logging degrades to console-only and NEVER throws.
 *   * run_id is generated by Postgres (scrape_runs.id default gen_random_uuid())
 *     and read back from the INSERT — so there is NO `uuid` dependency.
 *   * Console MIRROR is OPT-IN via RUNLOGGER_CONSOLE=on (default OFF). The
 *     orchestrator already prints every one of these events via runManager.log, so
 *     mirroring by default would double every line in the live terminal. Events are
 *     ALWAYS written to the DB regardless of the mirror setting.
 *   * A failed batch flush is logged to console and swallowed — a logging failure
 *     must never kill a scrape.
 */

const os = require('os');
const { getSupabaseClient } = require('../db/supabase');

const FLUSH_INTERVAL_MS = 5000;
const FLUSH_BATCH_SIZE = 100;
const CONSOLE_MIRROR = process.env.RUNLOGGER_CONSOLE === 'on';

class RunLogger {
  constructor() {
    this.runId = null;
    this.buffer = [];
    this.flushTimer = null;
    this.counters = null;
    this.finished = false;
    this.consoleMirror = CONSOLE_MIRROR;
  }

  async startRun({ trigger = 'manual', configSnapshot = {}, scraperVersion = null } = {}) {
    this.finished = false;
    this.buffer = [];
    // Clamp trigger to the CHECK constraint values.
    const safeTrigger = ['manual', 'scheduled', 'cli'].includes(trigger) ? trigger : 'manual';

    const client = getSupabaseClient();
    if (client) {
      try {
        const { data, error } = await client
          .from('scrape_runs')
          .insert({
            trigger: safeTrigger,
            config_snapshot: configSnapshot,
            hostname: os.hostname(),
            scraper_version: scraperVersion,
          })
          .select('id')
          .single();
        if (error) throw error;
        this.runId = data.id;
        console.log(`[runLogger] started run ${this.runId}`);
      } catch (err) {
        console.error('[runLogger] failed to create scrape_runs row:', err.message);
        this.runId = null; // logging becomes console-only for this run
      }
    } else {
      this.runId = null;
      console.log('[runLogger] Supabase not configured — run logging disabled (console-only).');
    }

    this.counters = {
      councils_attempted: 0,
      councils_succeeded: 0,
      councils_failed: 0,
      applications_seen: 0,
      applications_scraped_ok: 0,
      applications_scraped_failed: 0,
      applications_skipped_terminal: 0,
      applications_skipped_filter: 0,
      applications_skipped_no_docs: 0,
      documents_downloaded: 0,
      documents_skipped_known: 0,
      documents_failed: 0,
    };

    // Periodic flush. unref() so the timer never keeps the process alive on its own.
    this.flushTimer = setInterval(() => {
      this.flush().catch(err => console.error('[runLogger] scheduled flush error:', err.message));
    }, FLUSH_INTERVAL_MS);
    if (this.flushTimer.unref) this.flushTimer.unref();

    return this.runId;
  }

  event({ level = 'info', stage, council = null, applicationUid = null, adapter = null, message, details = null, durationMs = null }) {
    if (this.consoleMirror) {
      const line = `[${level}] [${stage}]${council ? ` [${council}]` : ''}${applicationUid ? ` [${applicationUid}]` : ''} ${message}`;
      if (level === 'error') console.error(line);
      else if (level === 'warn') console.warn(line);
      else console.log(line);
    }

    if (!this.runId) return; // no run row → DB logging disabled

    this.buffer.push({
      run_id: this.runId,
      level,
      stage,
      council,
      application_uid: applicationUid,
      adapter,
      message,
      details,
      duration_ms: durationMs,
    });

    if (this.buffer.length >= FLUSH_BATCH_SIZE) {
      this.flush().catch(err => console.error('[runLogger] size-triggered flush error:', err.message));
    }
  }

  info(args) { this.event({ ...args, level: 'info' }); }
  warn(args) { this.event({ ...args, level: 'warn' }); }
  error(args) { this.event({ ...args, level: 'error' }); }

  incrementCounter(key, by = 1) {
    if (this.counters && key in this.counters) this.counters[key] += by;
  }

  async flush() {
    if (this.buffer.length === 0) return;
    const client = getSupabaseClient();
    if (!client) { this.buffer.length = 0; return; }
    const batch = this.buffer.splice(0, this.buffer.length);
    try {
      const { error } = await client.from('scrape_events').insert(batch);
      if (error) throw error;
    } catch (err) {
      // Do NOT retry — the buffer is already drained. Never kill the scrape.
      console.error(`[runLogger] flush failed (${batch.length} events lost): ${err.message}`);
    }
  }

  async finishRun({ status = 'completed', errorSummary = null } = {}) {
    if (this.finished) return;
    this.finished = true;

    if (this.flushTimer) {
      clearInterval(this.flushTimer);
      this.flushTimer = null;
    }
    await this.flush();

    if (!this.runId) return;
    const client = getSupabaseClient();
    if (!client) return;

    try {
      const { error } = await client
        .from('scrape_runs')
        .update({
          finished_at: new Date().toISOString(),
          status,
          error_summary: errorSummary,
          ...this.counters,
        })
        .eq('id', this.runId);
      if (error) throw error;
      console.log(`[runLogger] finished run ${this.runId} status=${status}`);
    } catch (err) {
      console.error('[runLogger] failed to finalize run:', err.message);
    }
  }
}

module.exports = new RunLogger();
